version: '3'

services:

  init:
    build:
      context: ./init
    volumes:
      - static:/data

  server:
    image: nginx
    volumes:
      - static:/usr/share/ngnix/html
    ports:
      - "8080:80"
volumes:
  static: